services:
  - type: web
    name: flickr-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node src/server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: ACCESS_TOKEN_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
      - key: PORT
        value: 8080
